In [2]:
print("Hello World")

Hello World

In [3]:
from pathlib import Path
import pandas as pd

root = Path.cwd()

data_dir = root/"data"
books = data_dir/"03_Library Systembook.csv"
customers = data_dir/"03_Library SystemCustomers.csv"

books_df = pd.read_csv(books)
cust_df = pd.read_csv(customers)

print("Books shape", books_df.shape)
print("Customer shape:", cust_df.shape)

books_df.head(2), cust_df.head(2)

Books shape (114, 6)
Customer shape: (9, 2)

(    Id                             Books Book checkout Book Returned  \
 0  1.0               Catcher in the Rye   "20/02/2023"    25/02/2023
 1  2.0  Lord of the rings the two towers  "24/03/2023"    21/03/2023

   Days allowed to borrow  Customer ID
 0                2 weeks          1.0
 1                2 weeks          2.0  ,
    Customer ID Customer Name
 0          1.0      Jane Doe
 1          2.0    John Smith)

In [4]:
books_df["Id"] = books_df["Id"].astype(int)
books_df["Book checkout"] = books_df["Books checkout"].str.replace(r'^["\']|["\']$','', regex =True)
books_df["Books"] = books_df["Books"].str.title()

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
books_df.head(5)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [ ]:
books_df["Books"] = books_df["Books"].str.title()

In [ ]:
books_df.head(5)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher In The Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord Of The Rings The Two Towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord Of The Rings The Return Of The Kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The Hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [ ]:
type(books_df["Book Returned"])

pandas.core.series.Series

In [ ]:
print(type(books_df["Book Returned"]))

<class 'pandas.core.series.Series'>

In [7]:
books_df["Days allowed to borrow"] = books_df["Days allowed to borrow"].str.replace(r"\bweeks\b","",regex = True)

In [ ]:
books_df.head(5)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher In The Rye,"""20/02/2023""",25/02/2023,2,1.0
1,2.0,Lord Of The Rings The Two Towers,"""24/03/2023""",21/03/2023,2,2.0
2,3.0,Lord Of The Rings The Return Of The Kind,"""29/03/2023""",25/03/2023,2,3.0
3,4.0,The Hobbit,"""02/04/2023""",25/03/2023,2,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2,5.0

In [ ]:
print(type(books_df["Days allowed to borrow"]))

NameError: name 'books_df' is not defined

In [5]:
print(type[books_df["Days allowed to borrow"]])

type[0      2 weeks
1      2 weeks
2      2 weeks
3      2 weeks
4      2 weeks
        ...
109        NaN
110        NaN
111        NaN
112        NaN
113        NaN
Name: Days allowed to borrow, Length: 114, dtype: object]

In [8]:
books_df["Days allowed to borrow"].head(5)

0    2
1    2
2    2
3    2
4    2
Name: Days allowed to borrow, dtype: object

In [11]:
import pandas as pd
books_df["Days allowed to borrow"] = books_df["Days allowed to borrow"].astype(str).astype(int)

ValueError: invalid literal for int() with base 10: 'nan'

In [14]:
books_df['Days allowed to borrow'].value_counts()
books_df['Days allowed to borrow'] = books_df['Days allowed to borrow']*7

In [15]:
books_df.head(5)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 2 2 2 2 2 2,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 2 2 2 2 2 2,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 2 2 2 2 2 2,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 2 2 2 2 2 2,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 2 2 2 2 2 2,5.0

In [16]:
print(books_df['Days allowed to borrow'].dtype)

object

In [19]:
books_df['Days allowed to borrow'] = books_df['Days allowed to borrow'].str[0]

In [20]:
books_df.head(5)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2,5.0

In [24]:
books_df.tail(n=20)

     Id Books Book checkout Book Returned Days allowed to borrow  Customer ID
94  NaN   NaN           NaN           NaN                    NaN          NaN
95  NaN   NaN           NaN           NaN                    NaN          NaN
96  NaN   NaN           NaN           NaN                    NaN          NaN
97  NaN   NaN           NaN           NaN                    NaN          NaN
98  NaN   NaN           NaN           NaN                    NaN          NaN
99  NaN   NaN           NaN           NaN                    NaN          NaN
100 NaN   NaN           NaN           NaN                    NaN          NaN
101 NaN   NaN           NaN           NaN                    NaN          NaN
102 NaN   NaN           NaN           NaN                    NaN          NaN
103 NaN   NaN           NaN           NaN                    NaN          NaN
104 NaN   NaN           NaN           NaN                    NaN          NaN
105 NaN   NaN           NaN           NaN                    NaN          NaN
106 NaN   NaN           NaN           NaN                    NaN          NaN
107 NaN   NaN           NaN           NaN                    NaN          NaN
108 NaN   NaN           NaN           NaN                    NaN          NaN
109 NaN   NaN           NaN           NaN                    NaN          NaN
110 NaN   NaN           NaN           NaN                    NaN          NaN
111 NaN   NaN           NaN           NaN                    NaN          NaN
112 NaN   NaN           NaN           NaN                    NaN          NaN
113 NaN   NaN           NaN           NaN                    NaN          NaN

In [28]:
books_df.head(50)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,2,1.0
6,7.0,IT,"""10/04/2063""",03/04/2023,2,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,2,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,2,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,2,2.0
10,11.0,1984,"""23/04/2023""",27/04/2023,2,8.0
11,12.0,Little Women,"""02/04/2023""",01/05/2023,2,1.0
12,13.0,East of Eden,"""30/04/2023""",05/05/2023,2,2.0
13,14.0,America Is in the Heart,"""01/05/2023""",07/05/2023,2,3.0
14,15.0,Wuthering Heights,"""01/05/2023""",10/05/2023,2,9.0
15,16.0,Dark Tales,"""15/05/2023""",01/06/2023,2,2.0
16,17.0,The Bloody Chamber,"""32/05/2023""",04/06/2023,2,3.0
17,18.0,Les Miserables,"""03/06/2023""",07/06/2023,2,5.0
18,19.0,Dracula,"""10/06/2023""",10/07/2023,2,10.0
19,20.0,Frankenstein,"""01/06/2023""",20/06/2023,2,2.0

In [27]:
books_df = books_df.dropna()

In [25]:
books_df = books_df[books_df['Days allowed to borrow'] != 'NaN']

In [ ]:
books_df['Days allowed to borrow'] = books_df['Days allowed to borrow'].astype(int)
books_df.head(20)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,2,1.0
6,7.0,IT,"""10/04/2063""",03/04/2023,2,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,2,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,2,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,2,2.0
10,11.0,1984,"""23/04/2023""",27/04/2023,2,8.0
11,12.0,Little Women,"""02/04/2023""",01/05/2023,2,1.0
12,13.0,East of Eden,"""30/04/2023""",05/05/2023,2,2.0
13,14.0,America Is in the Heart,"""01/05/2023""",07/05/2023,2,3.0
14,15.0,Wuthering Heights,"""01/05/2023""",10/05/2023,2,9.0
15,16.0,Dark Tales,"""15/05/2023""",01/06/2023,2,2.0
16,17.0,The Bloody Chamber,"""32/05/2023""",04/06/2023,2,3.0
17,18.0,Les Miserables,"""03/06/2023""",07/06/2023,2,5.0
18,19.0,Dracula,"""10/06/2023""",10/07/2023,2,10.0
19,20.0,Frankenstein,"""01/06/2023""",20/06/2023,2,2.0

In [31]:
print(books_df['Days allowed to borrow'].dtype)

int32

In [32]:
books_df['Days allowed to borrow'] = books_df['Days allowed to borrow']*7

In [33]:
books_df.head(20)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,14,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,14,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,14,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,14,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,14,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,14,1.0
6,7.0,IT,"""10/04/2063""",03/04/2023,14,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,14,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,14,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,14,2.0
10,11.0,1984,"""23/04/2023""",27/04/2023,14,8.0
11,12.0,Little Women,"""02/04/2023""",01/05/2023,14,1.0
12,13.0,East of Eden,"""30/04/2023""",05/05/2023,14,2.0
13,14.0,America Is in the Heart,"""01/05/2023""",07/05/2023,14,3.0
14,15.0,Wuthering Heights,"""01/05/2023""",10/05/2023,14,9.0
15,16.0,Dark Tales,"""15/05/2023""",01/06/2023,14,2.0
16,17.0,The Bloody Chamber,"""32/05/2023""",04/06/2023,14,3.0
17,18.0,Les Miserables,"""03/06/2023""",07/06/2023,14,5.0
18,19.0,Dracula,"""10/06/2023""",10/07/2023,14,10.0
19,20.0,Frankenstein,"""01/06/2023""",20/06/2023,14,2.0